[build]
  publish = "_site"
  command = "DEBUG=* npm run build"

[[headers]]
  for = "/js/*"

  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"

[[headers]]
  for = "/css/*"

  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"

[[headers]]
  for = "/fonts/*"

  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"

# Manifest images are currently mutable and not hashed, so we only
# cache them for up to one day (60 * 60 * 24)
[[headers]]
  for = "/img/manifestImages/*"

  [headers.values]
    Cache-Control = '''
    public,
    max-age=86400'''
